### PR TITLE
Support child ViewModels

### LINKED ISSUE #39: Crash in collapsible view with child view model (iOS)
I have a `KMMViewModel` subclass that contains a child view model that's also a `KMMViewModel` subclass. The child view model is passed to a child view that is collapsible. I can collapse the view fine, but the app crashes when I try to expand it again.

### Relevant stack trace excerpt

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0  libobjc.A.dylib  0x104d49454 objc_retain + 16
1  iosApp           0x1049d2520 observableViewModel<A>(for:) + 104
2  iosApp           0x1049d1414 ObservedViewModel.init(wrappedValue:) + 68
3  iosApp           0x1049cd000 ChildView.init(viewModel:) + 180 (RootScreen.swift:30)
4  iosApp           0x1049cc914 closure #1 in RootScreen.body.getter + 1004 (RootScreen.swift:19)
5  iosApp           0x1049ccce0 partial apply for closure #1 in RootScreen.body.getter + 16
6  SwiftUI          0x1062294d0 0x105654000 + 12408016
7  iosApp           0x1049cc4bc RootScreen.body.getter + 344 (RootScreen.swift:10)
```

### Kotlin view models:

```kotlin
open class RootViewModel : KMMViewModel() {
    @NativeCoroutinesState
    val childViewModel: MutableStateFlow<ChildViewModel> = MutableStateFlow(viewModelScope, ChildViewModel("Child"))
}

open class ChildViewModel(name: String) : KMMViewModel() {
    @NativeCoroutinesState
    val name: MutableStateFlow<String> = MutableStateFlow(viewModelScope, name)
}
```

### Swift Views

```swift

struct RootScreen: View {
    @StateViewModel var viewModel = RootViewModel()
    @State private var isExpanded: Bool = true

    var body: some View {
        HStack {
            Button(
                action: { isExpanded.toggle() },
                label: { Image(systemName: isExpanded ? "chevron.right" : "chevron.left") }
            )

            if (isExpanded) {
                ChildView(viewModel: viewModel.childViewModel)
            }

            Spacer()
        }
        .padding()
    }
}

struct ChildView: View {
    @ObservedViewModel var viewModel: ChildViewModel

    init(viewModel: ChildViewModel) {
        _viewModel = ObservedViewModel(wrappedValue: viewModel)
    }

    var body: some View {
        Text(viewModel.name)
    }
}
```

### Sample project to demonstrate

https://github.com/humblehacker/KMMViewModelCrashExample

#### steps:

- Tap the chevron `>` to collapse the view
- Tap again to expand 💥

### Comments

It looks like when the view is collapsed, the child view model is destroyed. So when it's expanded again it crashes when we try to set the associated object on a dangling pointer.

Is there a better way to model this kind of relationship that might avoid this problem?

### PR DESCRIPTION
**Pull request by rickclephas**
Fixes #39

Usage:
```swift
extension MyParentViewModel {
    var myChildViewModel: MyChildViewModel {
        childViewModel(__myChildViewModel, at: \.__myChildViewModel)
    }
}
```

### CODE REVIEW

**Comment by humblehacker** [comment]
Yes, which is not uncommon in our codebase. Also consider lists of child view models.

**Comment by rickclephas** [comment]
Actually we could fix that by using `@ShouldRefineInSwift` and an extension property instead of a subclass.

**Comment by rickclephas** [comment]
@humblehacker do you have an example of such lists? I mean is it just a regular list containing `KMMViewModel`s?

**Comment by humblehacker** [comment]
We have this, for example: 
```kotlin
    @NativeCoroutinesState
    val tasks: StateFlow<List<TaskViewModel>> = mutableTasks.asStateFlow()
```

**Comment by rickclephas** [comment]
Alright, that should be doable. Do you see any other potential issues or challenges?

**Comment by humblehacker** [comment]
We also have maps of view models like this:

```kotlin
    @NativeCoroutinesState
    val things: StateFlow<Map<Item, ThingViewModel>?> = mutableThings.asStateFlow()
```

**Comment by ldobransky** [comment]
> Fixes #39
> 
> Usage:
> 
> ```swift
> extension MyParentViewModel {
>     var myChildViewModel: MyChildViewModel {
>         childViewModel(__myChildViewModel, at: \.__myChildViewModel)
>     }
> }
> ```

hello, I am facing with the issue regarding child viewmodels, but when I am trying to write extension, I am getting error like Cannot find 'childViewModels' in scope. Something was changed in new versions? I changed in parent viewmodel annotation for inner viewmodel and I wanna write that block of the code above, but I am getting issue. can you help me?

**Comment by rickclephas** [comment]
@ldobransky the `childViewModel` functions should be available in [v1.0.0-ALPHA-10](https://github.com/rickclephas/KMM-ViewModel/releases/tag/v1.0.0-ALPHA-10) and above.
If for some reason they aren't please open an issue with some reproduction code.

**Pull request merged**
